language: c

branches:
  only:
    - master
    - multiparams

addons:
  apt:
    packages:
    - ocaml
    - camlidl
    - libgmp-dev

cache:
  apt: true
  directories:
  - $HOME/.stack

env:
 - RESOLVER="lts-2.22"           SMT=z3   TESTS=Unit/
 - RESOLVER="lts-2.22"           SMT=z3   TESTS=Benchmarks/text
 - RESOLVER="lts-2.22"           SMT=z3   TESTS=Benchmarks/bytestring
 - RESOLVER="lts-2.22"           SMT=z3   TESTS=Benchmarks/esop
 - RESOLVER="lts-2.22"           SMT=z3   TESTS=Benchmarks/vect-algs
 - RESOLVER="lts-2.22"           SMT=z3   TESTS=Benchmarks/icfp*

 - RESOLVER="nightly-2015-09-24" SMT=z3   TESTS=Unit/
 - RESOLVER="nightly-2015-09-24" SMT=z3   TESTS=Benchmarks/text
 - RESOLVER="nightly-2015-09-24" SMT=z3   TESTS=Benchmarks/bytestring
 - RESOLVER="nightly-2015-09-24" SMT=z3   TESTS=Benchmarks/esop
 - RESOLVER="nightly-2015-09-24" SMT=z3   TESTS=Benchmarks/vect-algs
 - RESOLVER="nightly-2015-09-24" SMT=z3   TESTS=Benchmarks/icfp*

 # ugh... Classify.hs is too slow and makes travis think the build is stalled
 # - TESTS=hscolour

install:
 - scripts/travis install_smt "$SMT"
 - scripts/travis install_stack
 - scripts/travis configure_stack "$RESOLVER"
 - scripts/travis setup_ghc
 - scripts/travis install_dependencies

script:
 - scripts/travis do_build && scripts/travis do_test "$TESTS" "$SMT"

after_failure:
 - scripts/travis dump_fail_logs

