language: haskell

sudo: false

cache:
  apt: true
  directories:
      - $HOME/.cabal

addons:
  apt_packages:
  - fuse

env:
 - SMT=z3 TESTS=Unit/pos
 - SMT=z3 TESTS=Unit/neg
 - SMT=z3 TESTS=Unit/crash
 - SMT=z3 TESTS=Benchmarks/text
 - SMT=z3 TESTS=Benchmarks/bytestring
 - SMT=z3 TESTS=Benchmarks/esop
 - SMT=z3 TESTS=Benchmarks/vector-algorithms
 - SMT=cvc4 TESTS=Unit/pos
 - SMT=cvc4 TESTS=Unit/neg
 - SMT=cvc4 TESTS=Unit/crash
 - SMT=z3 TESTS=Unit/icfp_pos
 - SMT=z3 TESTS=Unit/icfp_neg
 # ugh... Classify.hs is too slow and makes travis think the build is stalled
 # - TESTS=hscolour

ghc: 7.8

install:
 - apt-cache policy fuse
 - stat /dev/fuse
 - scripts/travis setup_env

script:
 - scripts/travis boxme

