# TODO: this is broken as travis does not support fuse

language: c
before_install:
  - sudo apt-get update -qq
install:
  - sudo apt-get install -qq fuse fuse-utils libfuse-dev
  - sudo apt-get install -qq python3 user-mode-linux
  - sudo mknod /dev/fuse c 10 229
  - sudo chmod 666 /dev/fuse
  - cmake .
  - make
script: ./umltest.sh
